{
    "targets":
    [
        {
            "target_name": "windows_installer",
            "sources":
            [
                "./src/database.cc",
                "./src/record.cc",
                "./src/summary-information.cc",
                "./src/view.cc",
                "./src/windows-installer.cc"
            ],
            "libraries":
            [
                "msi"
            ]
        }
    ]
}
